*** Variables ***
${PRODUCTS_LABEL}       //span[text()='Products']
${INVENTORY_ITEM}       xpath=(//div[@class='inventory_item_img'])
${INVENTORY_PRICE}      xpath=//div[@class='inventory_details_price']
${ADD_TO_CART_BUTTON}   //button[text()='Add to cart']
${BACK_TO_PRODUCTS_BUTTON}  //button[@id='back-to-products']
${SHOPPING_CART_LINK}    class=shopping_cart_link
${CHECKOUT_BUTTON}      //button[@id='checkout']
